### ISSUE TITLE
Automated testing failure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/forces-and-motion-basics#222]
I'll see if I can reproduce somehow, since this seems to be fairly reliably happening (just this sim):
```
forces-and-motion-basics : fuzz : require.js : run
Uncaught Error: Module name "FORCES_AND_MOTION_BASICS/forcesAndMotionBasics" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
Error: Module name "FORCES_AND_MOTION_BASICS/forcesAndMotionBasics" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:166:13)
    at Object.localRequire [as require] (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:1392:30)
    at requirejs (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:1737:20)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/forces-and-motion-basics/js/motion/MotionConstants.js?bust=1489645707404:11:31
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:866:35)
    at Module.enable (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:1143:14)
    at Module.init (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:1170:55)
    at Object.completeLoad (https://bayes.colorado.edu/continuous-testing/snapshot-1489645593551/sherpa/lib/require-2.1.11.js:1544:11)
Approximately 3/16/2017, 12:26:33 AM
```

Maybe there's something weird going on with namespaces?

**Comment by jessegreenberg** [comment]
I haven't been able to reproduce this at all myself. I let the sim fuzzTest for about 4 minutes for built and requirejs versions.  I cannot reproduce in test-server.

But I do see it in https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html, is it possible that this is an issue with continuous testing?

**Comment by jessegreenberg** [comment]
Like bayes isn't able to pull latest or something?

**Comment by jonathanolson** [comment]
> is it possible that this is an issue with continuous testing?

That may happen, but it's only happening with this sim. I'll be looking into it.

**Comment by phet-steele** [comment]
@jonathanolson @jessegreenberg this line: https://github.com/phetsims/forces-and-motion-basics/blob/master/js/motion/MotionConstants.js#L8

needs to say `define( function( require ) {...}`, it's currently missing "require". That's my guess.

**Comment by jonathanolson** [comment]
Recommended fix pushed, let me know if it fixes it?

**Comment by samreid** [comment]
It looks like Bayes reports this as fixed, and it is working again in my local aqua test.  Other sims exhibit the missing `require`:

area-builder
energy-forms-and-changes
energy-skate-park-basics
fluid-pressure-and-flow

I'll create a new issue to investigate.
