### ISSUE TITLE
CT passed-in thumbNode must have the correct tandem

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#287]
```
forces-and-motion-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/forces-and-motion-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618238625034%22%2C%22timestamp%22%3A1618242258633%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new AppliedForceSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/AppliedForceSlider.js:35:5)
at new MotionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/MotionScreenView.js:134:32)
at MotionScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/MotionScreen.js:29:16)
at MotionScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 8:43:45 AM

----------------------------------

forces-and-motion-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/phet-io-wrappers/mirror-inputs/?sim=forces-and-motion-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618238625034%22%2C%22timestamp%22%3A1618241290411%7D
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new AppliedForceSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/AppliedForceSlider.js:35:5)
at new MotionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/MotionScreenView.js:134:32)
at MotionScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/MotionScreen.js:29:16)
at MotionScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 8:43:45 AM

----------------------------------

forces-and-motion-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/studio/?sim=forces-and-motion-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618238625034%22%2C%22timestamp%22%3A1618239902536%7D
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new AppliedForceSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/AppliedForceSlider.js:35:5)
at new MotionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/MotionScreenView.js:134:32)
at MotionScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/MotionScreen.js:29:16)
at MotionScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 8:43:45 AM

----------------------------------

forces-and-motion-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/phet-io-wrappers/phet-io-wrappers-tests.html?sim=forces-and-motion-basics&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: forces-and-motion-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new AppliedForceSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/AppliedForceSlider.js:35:5)
at new MotionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/MotionScreenView.js:134:32)
at MotionScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/MotionScreen.js:29:16)
at MotionScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:932:25

Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnobError: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.thumb, actual: forcesAndMotionBasics.motionScreen.view.appliedForceSlider.sliderKnob
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new AppliedForceSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/AppliedForceSlider.js:35:5)
at new MotionScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/view/MotionScreenView.js:134:32)
at MotionScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/forces-and-motion-basics/js/motion/MotionScreen.js:29:16)
at MotionScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:924:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Sim.js:932:25
id: Bayes Chrome
Snapshot from 4/12/2021, 8:43:45 AM
```

**Comment by marlitas** [comment]
This must have been fixed somewhere else, because I do not see the error coming up in CT. closing.
