### ISSUE TITLE
CT tried to removeListener on something that wasn't a listener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#290]
```
forces-and-motion-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/phet-io-wrappers/state/?sim=forces-and-motion-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634031115761%22%2C%22timestamp%22%3A1634039576151%7D
Uncaught Error: Uncaught Error: Assertion failed: tried to removeListener on something that wasn't a listener
Error: Assertion failed: tried to removeListener on something that wasn't a listener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/assert/js/assert.js:25:13)
at TinyProperty.removeListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/axon/js/TinyEmitter.js:135:7)
at TinyProperty.unlink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/axon/js/TinyProperty.js:180:10)
at NumberProperty.unlink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/axon/js/Property.js:410:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/forces-and-motion-basics/js/netforce/model/Puller.js:89:27
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/axon/js/Property.js:275:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/axon/js/Property.js:187:14)
at NetForceModel.movePullerToKnot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/forces-and-motion-basics/js/netforce/model/NetForceModel.js:200:27)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634031115761/forces-and-motion-basics/js/netforce/model/NetForceModel.js:169:14
id: Bayes Chrome
Snapshot from 10/12/2021, 3:31:55 AM
```

**Comment by marlitas** [comment]
I do not see this error in the last 40 columns of CT. Closing as stale.
