### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#297]
```
forces-and-motion-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/forces-and-motion-basics/forces-and-motion-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662000048857%22%2C%22timestamp%22%3A1662026310539%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:212:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (DelayedMutate.ts:82:19)
at mutate (DelayedMutate.ts:82:19)
at mutate (Sizable.ts:172:19)
at mutate (DelayedMutate.ts:82:19)
at mutate (FlowBox.ts:118:9)
at (VBox.ts:19:4)
id: Bayes Puppeteer
Snapshot from 8/31/2022, 8:40:48 PM

----------------------------------

forces-and-motion-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/phet-io-wrappers/state/?sim=forces-and-motion-basics&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662000048857%22%2C%22timestamp%22%3A1662032386811%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:212:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (DelayedMutate.ts:82:19)
at mutate (DelayedMutate.ts:82:19)
at mutate (Sizable.ts:172:19)
at mutate (DelayedMutate.ts:82:19)
at mutate (FlowBox.ts:118:9)
at (VBox.ts:19:4)
id: Bayes Puppeteer
Snapshot from 8/31/2022, 8:40:48 PM

----------------------------------

forces-and-motion-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/phet-io-wrappers/phet-io-wrappers-tests.html?sim=forces-and-motion-basics&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: forces-and-motion-basics: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/assert/js/assert.js:28:13)
at VerticalCheckboxGroup.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/tandem/js/PhetioObject.js:144:17)
at VerticalCheckboxGroup.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/nodes/Node.js:6368:11)
at VerticalCheckboxGroup.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/nodes/Node.js:6358:10)
at VerticalCheckboxGroup.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/util/DelayedMutate.js:70:20)
at VerticalCheckboxGroup.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/util/DelayedMutate.js:70:20)
at VerticalCheckboxGroup.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/layout/Sizable.js:110:20)
at VerticalCheckboxGroup.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/util/DelayedMutate.js:70:20)
at new FlowBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/layout/nodes/FlowBox.js:90:10)
at new VBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/chipper/dist/js/scenery/js/layout/nodes/VBox.js:13:5)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662000048857/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:212:16)
at initializePhetioObject (Node.ts:6321:10)
at initializePhetioObject (Node.ts:6311:9)
at mutate (DelayedMutate.ts:82:19)
at mutate (DelayedMutate.ts:82:19)
at mutate (Sizable.ts:172:19)
at mutate (DelayedMutate.ts:82:19)
at mutate (FlowBox.ts:118:9)
at (VBox.ts:19:4)
id: Bayes Puppeteer
Snapshot from 8/31/2022, 8:40:48 PM
```

**Comment by marlitas** [comment]
This is a stale issue. Probably fixed somewhere else.
