### ISSUE TITLE
CT Error: Assertion failed: reentry detected, value=3, oldValue=2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/forces-and-motion-basics#336]
```
forces-and-motion-basics : fuzz : unbuilt : listenerOrderRandom
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/forces-and-motion-basics/forces-and-motion-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1733346507502%22%2C%22timestamp%22%3A1733348276713%7D&brand=phet&ea&fuzz&listenerOrder=random
ERROR: QUERY: brand=phet&ea&fuzz&listenerOrder=random
Error: Assertion failed: reentry detected, value=3, oldValue=2
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/assert/js/assert.js:45:13
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/assert/js/assert.js:45:13)
    at assert (../../../../../axon/js/ReadOnlyProperty.ts:339:14)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:287:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:267:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at  (../../../../../axon/js/createObservableArray.ts:397:4)
    at push (../../../../../axon/js/createObservableArray.ts:448:39)
    at add (../../../../../../../forces-and-motion-basics/js/motion/view/ItemNode.ts:103:33)
    at moveToStack (../../../../../../../forces-and-motion-basics/js/motion/view/ItemNode.ts:179:10)
    at _end (../../../../../../scenery/js/listeners/DragListener.ts:352:24)
    at callback (../../../../../../scenery/js/listeners/PressListener.ts:759:16)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/listeners/PressListener.ts:512:24)
    at release (../../../../../../scenery/js/listeners/DragListener.ts:348:10)
    at release (../../../../../../scenery/js/listeners/PressListener.ts:858:11)
    at inputEvent (../../../../../../scenery/js/input/Input.ts:1875:91)
    at dispatchToListeners (../../../../../../scenery/js/input/Input.ts:1824:9)
    at dispatchEvent (../../../../../../scenery/js/input/Input.ts:1628:9)
    at upEvent (../../../../../../scenery/js/input/Input.ts:395:11)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/input/Input.ts:1194:23)
    at mouseUp (../../../../../../scenery/js/input/InputFuzzer.js:275:26)
    at mouseToggle (../../../../../../scenery/js/input/InputFuzzer.js:40:11)
    at action (../../../../../../scenery/js/input/InputFuzzer.js:107:6)
    at fuzzEvents (../../../../../joist/js/SimDisplay.ts:221:23)
    at fuzzInputEvents (../../../../../joist/js/Sim.ts:1043:44)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733346507502%2Fforces-and-motion-basics%2Fforces-and-motion-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1733346507502%22%2C%22timestamp%22%3A1733348276713%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733346507502%2Fforces-and-motion-basics%2Fforces-and-motion-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1733346507502%22%2C%22timestamp%22%3A1733348276713%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/forces-and-motion-basics/forces-and-motion-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1733346507502%22%2C%22timestamp%22%3A1733348276713%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[LOADED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733346507502%2Fforces-and-motion-basics%2Fforces-and-motion-basics_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22forces-and-motion-basics%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1733346507502%22%2C%22timestamp%22%3A1733348276713%7D
[CONSOLE] listenerOrder random seed: 595477
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/chipper/dist/js/tambo/js/phetAudioContext.js" line: 11}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733346507502/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  validation failed for value: 50 Property value not valid: Failed validation for validators[1]: Number value 50 must be within rangeProperty value: [Range (min:0 max:0)]: value failed isValidValue: 50 prunedValidator: {
  "valueType": "number",
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] Assertion failed:  reentry detected, value=1, oldValue=0
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=1
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[PAGE ERROR] Error: Assertion failed: validation failed for value:
 50
 Property value not valid: Failed validation for validators[1]: Number value 50 must be within rangeProperty value: [Range (min:0 max:0)]: value failed isValidValue: 50
 prunedValidator:
 {
  "valueType": "number",
  "valueComparisonStrategy": "reference",
  "phetioType": {
    "validator": {
      "valueType": "number",
      "validationMessage": "Validation failed IOType Validator: NumberIO"
    },
    "typeName": "NumberIO"
  },
  "validators": [
    {
      "validationMessage": "Should not be NaN"
    },
    {}
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=1, oldValue=0
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=1
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=3
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=3
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=3
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=3
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=3
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=[Range (min:0 max:0)], oldValue=[Range (min:0 max:0)]
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=[Range (min:0 max:0)], oldValue=[Range (min:0 max:0)]
[CONSOLE] Assertion failed:  reentry detected, value=2, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=2, oldValue=3
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=2
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=2
[CONSOLE] Assertion failed:  reentry detected, value=4, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=4, oldValue=3
[CONSOLE] Assertion failed:  reentry detected, value=3, oldValue=4
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=3, oldValue=4
[CONSOLE] Assertion failed:  reentry detected, value=4, oldValue=3
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=4, oldValue=3
[CONSOLE] Assertion failed:  reentry detected, value=5, oldValue=4
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] Assertion failed:  reentry detected, value=4, oldValue=5
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=5, oldValue=4
[CONSOLE] Assertion failed:  reentry detected, value=5, oldValue=4
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=4, oldValue=5
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=5, oldValue=4
[CONSOLE] Assertion failed:  reentry detected, value=4, oldValue=5
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] Assertion failed:  reentry detected, value=5, oldValue=4
[CONSOLE] Debug info: {
  "seed": 0.8888330327151664,
  "currentScreenName": "MotionScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
```

**Comment by marlitas** [comment]
This has been addressed above. I'm going to keep an eye out for CT.

**Comment by marlitas** [comment]
CT is looking green. I think this can be closed.
